### ISSUE TITLE
Error Runtime

### ISSUE THREAD

**Issue by blacknode** [alexyoung/ircd.js#97]
/home/*/*/ircd-node/node_modules/winston/lib/winston/logger.js:130
      level[LEVEL] = level.level;

TypeError: Cannot create property 'Symbol(level)' on string 'S: [null] :null!null@ip6-localhost NICK :newbie'
    at DerivedLogger.log (/home/undernode/projects/ircd-node/node_modules/winston/lib/winston/logger.js:130:20)
    at Object.winston.(anonymous function).args [as log] (/home/undernode/projects/ircd-node/node_modules/winston/lib/winston.js:101:55)
    at User.send (/home/undernode/projects/ircd-node/lib/user.js:85:13)
    at Commands.NICK (/home/undernode/projects/ircd-node/lib/commands.js:74:10)
    at Server.respondToMessage (/home/undernode/projects/ircd-node/lib/server.js:173:36)
    at Server.respond (/home/undernode/projects/ircd-node/lib/server.js:183:14)
    at Server.data (/home/undernode/projects/ircd-node/lib/server.js:321:10)
    at Carrier.<anonymous> (/home/undernode/projects/ircd-node/lib/server.js:278:51)
    at Carrier.emit (events.js:180:13)
    at /home/undernode/projects/ircd-node/node_modules/carrier/lib/carrier.js:24:12

**Comment by blacknode** [comment]
Thanks
